export const SportsList = [
  "Atletismo",
  "Badminton",
  "Basquete",
  "Basquete 3X3",
  "Boxe",
  "Breaking",
  "Canoagem de Velocidade",
  "Canoagem slalom",
  "Ciclismo BMX Freestyle",
  "Ciclismo BMX Racing",
  "Ciclismo de Estrada",
  "Ciclismo de Pista",
  "Ciclismo Mountain Bike",
  "Escalada",
  "Esgrima",
  "Futebol",
  "Ginástica Artística",
  "Ginástica de Trampolim",
  "Ginástica Rítmica",
  "Golfe",
  "Handebol",
  "Hipismo",
  "Hóquei sobre Grama",
  "Judô",
  "Levantamento de Peso",
  "Luta",
  "Maratona Aquática",
  "Nado Artístico",
  "Natação",
  "Pentatlo Moderno",
  "Polo Aquático",
  "Remo",
  "Rugby Sevens",
  "Saltos Ornamentais",
  "Skate",
  "Surfe",
  "Taekwondo",
  "Tênis",
  "Tênis de Mesa",
  "Tiro com Arco",
  "Tiro Esportivo",
  "Triatlo",
  "Vela",
  "Vôlei",
  "Vôlei de Praia",
];
